---
- name: Download UV installer
  ansible.builtin.get_url:
    url: https://astral.sh/uv/install.sh
    dest: /tmp/uv_install.sh
    mode: '0700'

- name: Run UV installer
  ansible.builtin.command: /usr/bin/env bash /tmp/uv_install.sh
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/uv"
