---
- name: Fetch uv installer
  ansible.builtin.uri:
    url: https://astral.sh/uv/install.sh
    return_content: true
  register: uv_installer

- name: Run uv installer
  ansible.builtin.shell:
    cmd: sh -s -- -y
    stdin: "{{ uv_installer.content }}"
