---
- name: Download Homebrew installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/install_homebrew.sh
    mode: '0700'

- name: Run Homebrew installer
  ansible.builtin.command: /usr/bin/env bash /tmp/install_homebrew.sh
  environment:
    NONINTERACTIVE: "1"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew

- name: Set LinuxBrew Executable Path
  ansible.builtin.set_fact:
    linuxbrew_executable: /home/linuxbrew/.linuxbrew/bin/brew
    linuxbrew_path: /home/linuxbrew/.linuxbrew/bin
  become: true
