---
- name: Download Rustup installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: '0700'

- name: Run Rustup installer
  ansible.builtin.command: /usr/bin/env bash /tmp/rustup.sh -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
